### ISSUE TITLE
Forum posting

### ISSUE THREAD

**Issue by SilvesterYu** [devk232/Discussion-Forum#12]
Hi, thank you for your amazing work! I would like to know where I can publish posts after logging in, as it currently shows me that "There are no posts in the database!" when I navigate to Dashboard. I would appreciate your help.

**Comment by devk232** [comment]
Hey! Sorry for replying too late.
There are too many bugs in the application currently, and this is one of them. Dashboard doesn't shows post creation button until it has at least one post. what you can do is that redirect to `/new-post` to create a post and then refresh the main page.
Also you can only create tags if you are a admin privileges. After creating tags by sending multiple post requests using any API testing tool, the front page looks something like this - 
![image](https://github.com/devk232/Discussion-Forum/assets/59441868/d060e40b-11c3-44ca-b2c8-2a5949a4905e)

**Comment by PGE77** [comment]
Hi, you can help me, how i can create tags ? Its possible add to react frontend default tags ? You can help me pls, I need create tags...

**Comment by devk232** [comment]
@PGE77 I still need to develop a frontend to create tags; you can give yourself admin privileges by manually changing the database entry. Then, you can use something like Postman to create tags by adding an authorisation token in your request header. Otherwise you can create tags manually too.
